version: '3.7'

services:
  mpp-backend:
    build:
      context: ./mpp-backend
    image: mpp-backend:backend
    container_name: mpp-backend
    ports:
      - 8000:8000
    command: gunicorn MPP_API.wsgi:application --bind 0.0.0.0:8000 --log-level=debug --timeout 9000 --workers=1 --threads=8 
    expose:
      - 8000
    volumes:
      - static_volume:/static
      - /etc/localtime:/etc/localtime
    env_file:
      - ./mpp-backend/MPP_API/.env.dev
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/
    env_file:
      - ./mpp-backend/MPP_API/.env.dev

  redis:
    image: "redis:alpine"

  celery:
    build: ./mpp-backend
    container_name: celery
    command: celery -A MPP_API worker -l INFO
    depends_on:
      - db
      - redis
    env_file:
      - ./mpp-backend/MPP_API/.env.dev

  celery-beat:
    build: ./mpp-backend
    container_name: celery-beat
    command: celery -A MPP_API beat -l INFO
    depends_on:
      - db
      - redis
    env_file:
      - ./mpp-backend/MPP_API/.env.dev
  
  mpp-frontend:
        build: ./mpp-frontend
        container_name: mpp-frontend
        ports:
            - "80:81"
            - "443:443"
        volumes:
            - ./:/mpp-frontend
            - /mpp-frontend/node_modules
            - ./certbot/conf:/etc/letsencrypt

volumes:
  postgres_data:
  static_volume:
